version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - 3003:3000
    
    networks:
      - backend

    restart: always

networks:
  backend:
    external: true