---
networks:
  backend:
    external: true
  frontend:
    external: true
volumes:
  db-data:
  minio-data:
services:
  db:
    container_name: backend_db
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U']
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend
      - frontend
  minio:
    container_name: minio
    image: minio/minio:RELEASE.2024-08-03T04-33-23Z-cpuv1
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
    networks:
      - backend
      - frontend

