version: '3'
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - 3003:3000
    
    networks:
      - backend
      - frontend

    restart: always

networks:
  backend:
    external: true
  frontend:
    external: true